### ISSUE TITLE
Conflicts with XLD 7.2.0

### ISSUE THREAD

**Issue by csmith-optum** [xebialabs-community/xld-custom-orchestrators-plugin#5]
Causes a conflict in XLD 7.2.0. that prevents deploying of any application packages.  Plugin must be removed in 7.2.0.

Reported in Zendesk ticket #9701

https://support.xebialabs.com/hc/requests/9701

**Comment by jdewinne** [comment]
Thanks for reporting. I've fixed this in [v7.2.0](https://github.com/xebialabs-community/xld-custom-orchestrators-plugin/releases/tag/v7.2.0).
